name: Deploy script

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy script'
        required: true
        default: 'true'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy
        env:
          HOSTINGER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          HOSTINGER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $HOSTINGER_USERNAME@$HOSTINGER_IP << 'EOF'
            cd ~/careers
            git pull origin master
            composer install --no-interaction --prefer-dist --optimize-autoloader
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm run build
            php artisan optimize:clear
          EOF
