name: Deploy script

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy script'
        required: true
        default: 'true'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hostinger
        env:
          HOSTINGER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          HOSTINGER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP << 'EOF'
            cd ~/careers
            git pull origin master
            composer2 install --no-interaction --prefer-dist --optimize-autoloader
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm run build
            php artisan optimize:clear
          EOF
